#! /bin/bash

if [ "$#" -lt 2 ]; then
	echo "O programa $0 requer nome do arquivo e arquivos a serem compactados"
	exit 1
fi

arquivo_saida="$1"
arquivos=("${@:2}")

for arquivo in "${arquivos[@]}"; do
  if [ ! -e "$arquivo" ]; then
    echo "Arquivo não encontrado: $arquivo"
    exit 1
  fi
done

tar -czf "$arquivo_saida" "${arquivos[@]}"

echo "Compactado com sucesso em $arquivo_saida"
